language: php

php:
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"

env:
  - CONTAO_VERSION=~3.2.0
  - CONTAO_VERSION=~3.3.0
  - CONTAO_VERSION=~3.4.0
  - CONTAO_VERSION=~3.5.0

# Exclude impossible Contao Version combinations.
matrix:
  exclude:
    - php: "5.3"
      env: CONTAO_VERSION=~3.5.0

sudo: false

install:
  - if [ -n "GITHUB_TOKEN" ]; then composer config github-oauth.github.com ${GITHUB_TOKEN}; fi;
  - travis_retry composer self-update && composer --version
  - travis_retry composer require contao/core $CONTAO_VERSION --no-update
  - travis_retry composer update --prefer-dist --no-interaction

script: ant -keep-going
